### PR TITLE
schedule: remove text shadow on h4

### PR DESCRIPTION
**Pull request by tormath1**
Signed-off-by: Mathieu Tortuyaux <mtortuyaux@microsoft.com>

<hr>

Before:
tmp f0uYQxepY3

After:
tmp bZzLlggqlF

### CODE REVIEW

**Comment by tormath1** [comment]
@pabluk if you could just regen css from this change?

**Review by pabluk — APPROVED** [review]
LGTM!

**Comment by pabluk** [comment]
> @pabluk if you could just regen css from this change?

Yes, of course :+1:

**Comment by pabluk** [comment]
I've also updated the submodule version on https://github.com/sre-summercamp/sre-summercamp.github.io/commit/253375d11cedd5c1d676a8fd4e8e1aced5b08d4d

**Comment by tormath1** [comment]
Thanks a lot!

**Pull request merged**
